"""
Compute and save PCA and LDA eigenvalues from the synthetic orderedBoth dataset.

Loads X_train from the synthetic dataset, computes:
  - PCA eigenvalues (variance per direction) via SVD of X_train
  - LDA explained-variance ratio via sklearn LinearDiscriminantAnalysis

Outputs (saved to ICMLWorkshop_weightSymmetry2026/eigenvalues/):
  pca_eigenvalues.npy           shape (p,)   raw PCA eigenvalues (σ²), decreasing
  pca_eigenvalues_norm.npy      shape (p,)   normalised so pca_eigenvalues_norm[0] = 1
  lda_eigenvalues.npy           shape (C-1,) sklearn explained_variance_ratio, sums to 1
  lda_eigenvalues_norm.npy      shape (C-1,) normalised so lda_eigenvalues_norm[0] = 1
  eigenvalues_pca_{stamp}.png   bar chart of normalised PCA eigenvalues
  eigenvalues_lda_{stamp}.png   bar chart of LDA explained-variance ratio

Usage:
    Conda environment: mrl_env

    python weight_symmetry/scripts/compute_eigenvalues.py
    python weight_symmetry/scripts/compute_eigenvalues.py --seed 47 --variant orderedBoth
"""

import argparse
import os
import sys
import time

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib as mpl

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_CODE_ROOT  = os.path.abspath(os.path.join(_SCRIPT_DIR, "..", ".."))
_PROJ_ROOT  = os.path.dirname(_CODE_ROOT)
for _p in [_CODE_ROOT]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

OUT_DIR = os.path.join(
    _PROJ_ROOT, "files", "results",
    "ICMLWorkshop_weightSymmetry2026", "eigenvalues"
)

PCA_BAR_COLOR = "#89C4E1"   # faded blue (matches style plan eigenvalue overlay)
LDA_BAR_COLOR = "#89C4E1"   # same faded blue for consistency


def _apply_style():
    mpl.rcParams.update({
        "font.family":      "serif",
        "font.size":        9,
        "axes.titlesize":   9,
        "axes.labelsize":   9,
        "xtick.labelsize":  8,
        "ytick.labelsize":  8,
        "legend.fontsize":  8,
        "figure.dpi":       150,
        "savefig.dpi":      300,
        "pdf.fonttype":     42,
        "ps.fonttype":      42,
    })


def _save(fig, name, stamp, out_dir):
    stem = f"{name}_{stamp}"
    for ext in ("pdf", "png", "svg"):
        fig.savefig(os.path.join(out_dir, f"{stem}.{ext}"), bbox_inches="tight")
    print(f"  Saved {stem}.{{pdf,png,svg}}")


def _plot_pca(pca_eigs_norm, stamp, out_dir):
    fig, ax = plt.subplots(figsize=(3.5, 2.5))
    xs = np.arange(1, len(pca_eigs_norm) + 1)
    ax.bar(xs, pca_eigs_norm, color=PCA_BAR_COLOR, alpha=0.85, width=0.8)
    ax.set_xlabel("Principal component")
    ax.set_ylabel("Normalised eigenvalue")
    ax.set_title("PCA spectrum — synthetic orderedBoth")
    ax.grid(True, linestyle="--", linewidth=0.4, alpha=0.5, color="gray")
    fig.tight_layout()
    _save(fig, "eigenvalues_pca", stamp, out_dir)
    plt.close(fig)


def _plot_lda(lda_eigs, stamp, out_dir):
    fig, ax = plt.subplots(figsize=(3.5, 2.5))
    xs = np.arange(1, len(lda_eigs) + 1)
    ax.bar(xs, lda_eigs, color=LDA_BAR_COLOR, alpha=0.85, width=0.8)
    ax.set_xlabel("LDA direction")
    ax.set_ylabel("Explained variance ratio")
    ax.set_title("LDA spectrum — synthetic orderedBoth")
    ax.grid(True, linestyle="--", linewidth=0.4, alpha=0.5, color="gray")
    fig.tight_layout()
    _save(fig, "eigenvalues_lda", stamp, out_dir)
    plt.close(fig)


def _write_readme(out_dir, args, X_tr, y_tr, pca_eigs, pca_eigs_norm,
                  lda_eigs, lda_eigs_norm, stamp):
    n_samples, n_features = X_tr.shape
    n_classes = len(np.unique(y_tr))
    n_pca = len(pca_eigs)
    n_lda = len(lda_eigs)

    lines = [
        "# Eigenvalues — Synthetic Dataset",
        "",
        "Generated by `weight_symmetry/scripts/compute_eigenvalues.py`.",
        f"Run timestamp: {stamp}",
        "",
        "---",
        "",
        "## Dataset",
        "",
        f"- **Variant**: `{args.variant}`",
        f"- **Seed**: {args.seed}",
        f"- **X_train shape**: {n_samples} samples × {n_features} features",
        f"- **Number of classes**: {n_classes}",
        "",
        "### Dataset construction (orderedBoth)",
        "",
        "The synthetic dataset is a designed PCA-vs-LDA divergence benchmark:",
        "",
        f"- **Noise block** (dims 0–{n_features - n_lda - 1}): {n_features - n_lda} dims drawn from",
        "  N(0, σ_noise² I) with geometrically decaying noise variances (noise_scale_decay=0.9).",
        "  High variance → PCA preferentially picks these dimensions.",
        f"- **Signal block** (dims {n_features - n_lda}–{n_features - 1}): {n_lda} dims with",
        "  class-specific means. Within-class variance is low (σ_signal=0.1).",
        "  LDA directions align with these axes.",
        "- **Ordered LDA**: class means constructed so signal dim j has class separability",
        "  proportional to class_sep × lda_scale_decay^j (geometrically decreasing).",
        "  This gives a ground-truth LDA ordering, analogous to how PCA directions are",
        "  ordered by variance.",
        "",
        "Key property: PCA subspace (noise block) and LDA subspace (signal block) are",
        "**orthogonal by construction**, creating a maximal divergence scenario.",
        "",
        "---",
        "",
        "## Files",
        "",
        "| File | Shape | Description |",
        "|------|-------|-------------|",
        f"| `pca_eigenvalues.npy` | ({n_pca},) | Raw PCA eigenvalues (σ² per PC), strictly decreasing |",
        f"| `pca_eigenvalues_norm.npy` | ({n_pca},) | PCA eigenvalues normalised so index-0 = 1.0 |",
        f"| `lda_eigenvalues.npy` | ({n_lda},) | sklearn LDA explained_variance_ratio (sums to 1) |",
        f"| `lda_eigenvalues_norm.npy` | ({n_lda},) | LDA eigenvalues normalised so index-0 = 1.0 |",
        f"| `eigenvalues_pca_{{stamp}}.{{pdf,png,svg}}` | — | Bar chart of normalised PCA eigenvalues |",
        f"| `eigenvalues_lda_{{stamp}}.{{pdf,png,svg}}` | — | Bar chart of LDA explained-variance ratio |",
        "",
        "---",
        "",
        "## PCA eigenvalues (normalised, first 10)",
        "",
        "Index 0 = top principal component (highest variance).",
        "",
        "| Index | Norm. eigenvalue |",
        "|-------|-----------------|",
    ]
    for i in range(min(10, n_pca)):
        lines.append(f"| {i:5d} | {pca_eigs_norm[i]:.6f} |")
    lines += [
        f"| ... | (total {n_pca} components) |",
        "",
        "---",
        "",
        "## LDA explained-variance ratio (all directions)",
        "",
        "Index 0 = most discriminative LDA direction.",
        "",
        "| Index | Expl. var. ratio | Norm. eigenvalue |",
        "|-------|-----------------|-----------------|",
    ]
    for i in range(n_lda):
        lines.append(f"| {i:5d} | {lda_eigs[i]:.6f}         | {lda_eigs_norm[i]:.6f}         |")
    lines += [
        "",
        "---",
        "",
        "## Usage in Fig 1",
        "",
        "The plotting script `weight_symmetry/scripts/plot_fig1_mse_pca_ce_lda.py` loads",
        "these arrays to draw background eigenvalue bars in the leftmost column panels:",
        "",
        "- Row 0 (cosine similarity to PCA): uses `pca_eigenvalues_norm.npy`, x up to k=20",
        "- Row 1 (cosine similarity to LDA): uses `lda_eigenvalues.npy`, x up to k=5",
        "",
        "Load with:",
        "```python",
        "import numpy as np",
        f'pca_norm = np.load("<this_dir>/pca_eigenvalues_norm.npy")',
        f'lda_evr  = np.load("<this_dir>/lda_eigenvalues.npy")',
        "```",
    ]

    readme_path = os.path.join(out_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Saved README.md")


def main():
    parser = argparse.ArgumentParser(description="Compute PCA/LDA eigenvalues from synthetic data")
    parser.add_argument("--seed",    type=int, default=47,
                        help="Dataset seed (default 47)")
    parser.add_argument("--variant", default="orderedBoth",
                        choices=["nonOrderedLDA", "orderedLDA", "orderedBoth"],
                        help="Synthetic variant (default orderedBoth)")
    parser.add_argument("--out-dir", default=None, help="Override output directory")
    args = parser.parse_args()

    from weight_symmetry.data.synthetic import load_synthetic, SYNTHETIC_VARIANTS
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

    out_dir = args.out_dir or OUT_DIR
    os.makedirs(out_dir, exist_ok=True)
    stamp = time.strftime("%Y_%m_%d__%H_%M_%S")

    print(f"[compute_eigenvalues] Loading synthetic variant='{args.variant}' seed={args.seed} ...")
    raw = load_synthetic(seed=args.seed, **SYNTHETIC_VARIANTS[args.variant])

    X_tr = raw["X_train"].astype(np.float64)
    y_tr = raw["y_train"]
    print(f"[compute_eigenvalues] X_train: {X_tr.shape},  classes: {len(np.unique(y_tr))}")

    # ── PCA eigenvalues ──────────────────────────────────────────────────────
    print("[compute_eigenvalues] Running SVD ...")
    _, s, _ = np.linalg.svd(X_tr, full_matrices=False)
    pca_eigs      = s ** 2
    pca_eigs_norm = pca_eigs / pca_eigs[0]

    # ── LDA explained-variance ratio ─────────────────────────────────────────
    print("[compute_eigenvalues] Fitting LDA ...")
    lda = LinearDiscriminantAnalysis()
    lda.fit(X_tr, y_tr)
    lda_eigs      = lda.explained_variance_ratio_
    lda_eigs_norm = lda_eigs / lda_eigs[0]

    # ── Save arrays ──────────────────────────────────────────────────────────
    npy_files = {
        "pca_eigenvalues.npy":      pca_eigs,
        "pca_eigenvalues_norm.npy": pca_eigs_norm,
        "lda_eigenvalues.npy":      lda_eigs,
        "lda_eigenvalues_norm.npy": lda_eigs_norm,
    }
    for fname, arr in npy_files.items():
        path = os.path.join(out_dir, fname)
        np.save(path, arr)
        print(f"  Saved {fname}  shape={arr.shape}  first3={arr[:3].round(4)}")

    # ── Save bar charts ───────────────────────────────────────────────────────
    _apply_style()
    _plot_pca(pca_eigs_norm, stamp, out_dir)
    _plot_lda(lda_eigs, stamp, out_dir)

    # ── Write README ─────────────────────────────────────────────────────────
    _write_readme(out_dir, args, X_tr, y_tr, pca_eigs, pca_eigs_norm,
                  lda_eigs, lda_eigs_norm, stamp)

    print(f"\n[compute_eigenvalues] Done. Output: {out_dir}")


if __name__ == "__main__":
    main()
